from .Adult import AdultTask
from .ArabicDiacritization import ArabicDiacritizationTask
from .ArabicParsing import ArabicParsingTask
from .ArabicPOS import ArabicPOSTask
from .ArabicSegmentation import ArabicSegmentationTask
from .Attentionworthy import AttentionworthyTask
from .Checkworthiness import CheckworthinessTask
from .ClaimDetection import ClaimDetectionTask
from .DemographyGender import DemographyGenderTask
from .DemographyLocation import DemographyLocationTask
from .DemographyNameInfo import DemographyNameInfoTask
from .DialectID import DialectIDTask
from .Emotion import EmotionTask
from .FactualityCOVID19 import FactualityCOVID19Task
from .FactualityKhouja20 import Khouja20FactualityTask
from .FactualityUnifiedFC import UnifiedFCFactualityTask
from .HarmfulDetection import HarmfulDetectionTask
from .HateSpeech import HateSpeechTask
from .Lemmatization import LemmatizationTask
from .MachineTranslation import MachineTranslationTask
from .MultilabelPropaganda import MultilabelPropagandaTask
from .NER import NERTask
from .NewsCatAkhbarona import NewsCatAkhbaronaTask
from .NewsCatAlArabiya import NewsCatAlArabiyaTask
from .NewsCatAlKhaleej import NewsCatAlKhaleejTask
from .NewsCatASND import NewsCatASNDTask
from .Offensive import OffensiveTask
from .Q2QSimDetect import Q2QSimDetectionTask
from .QA import QATask
from .Sarcasm import SarcasmTask
from .Sentiment import SentimentTask
from .Spam import SpamTask
from .StanceKhouja20 import Khouja20StanceTask
from .StanceUnifiedFC import UnifiedFCStanceTask
from .STSTrack1 import STSTrack1Task
from .STSTrack2 import STSTrack2Task
from .Subjectivity import SubjectivityTask
from .XNLI import XNLITask
